/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '375px',
      },
      colors: {
        'tertiary-fixed': '#ffddb3',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#291800',
        'inverse-primary': '#abc8f4',
        'surface-tint': '#426086',
        'outline': '#73777f',
        'secondary-container': '#cbe7f5',
        'surface-container': '#d9f2ff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#cbe7f5',
        'on-surface-variant': '#43474e',
        'primary-fixed-dim': '#abc8f4',
        'surface-container-low': '#e6f6ff',
        'on-secondary-container': '#4e6874',
        'surface-container-high': '#ceedfd',
        'on-background': '#001f2a',
        'outline-variant': '#c3c6cf',
        'on-tertiary-fixed-variant': '#60400b',
        'on-error': '#ffffff',
        'primary-container': '#1b3b5f',
        'secondary-fixed-dim': '#afcbd8',
        'surface-variant': '#c9e7f7',
        'inverse-on-surface': '#e0f4ff',
        'surface': '#f4faff',
        'surface-bright': '#f4faff',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#c89c5f',
        'error': '#ba1a1a',
        'tertiary': '#352000',
        'on-surface': '#001f2a',
        'surface-container-highest': '#c9e7f7',
        'primary': '#002547',
        'surface-dim': '#c0dfee',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary-fixed-dim': '#eebe7e',
        'inverse-surface': '#163440',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#021f29',
        'secondary': '#48626e',
        'tertiary-container': '#523400',
        'background': '#f4faff',
        'on-primary-fixed-variant': '#2a486d',
        'on-primary-fixed': '#001c38',
        'primary-fixed': '#d3e4ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#88a6cf',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Public Sans', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
